name: "Build"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master

    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: 14.16

    - name: Install dependencies
      run: npm install

    - name: Build and deploy to GitHub
      run: GH_TOKEN=${{ secrets.github_token }} npm run dist

    - name: Deploy to website
      run: /home/portasynthinca3/yamka_electron_deploy.py